{
  modulesPath,
  lib,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # stuff originally generated by `sudo nixos-generate-config`
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/bf8d12df-92cf-439f-8f16-0b546ab4b928";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F379-10EB";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  networking.interfaces.wlp59s0.useDHCP = lib.mkDefault true;

  # idk if I still need these but my boot was broken
  hardware.graphics.enable = true;
  hardware.nvidia = {
    modesetting.enable = true;

    # this makes GPU used all the time instead of offloading it, worse for battery
    powerManagement.enable = false;
    powerManagement.finegrained = false;
    prime = {
      offload.enable = false;
      sync.enable = true;

      # fetched from `lspci` (nixpkgs#pciutils)
      intelBusId = "PCI:0:2:0";
      nvidiaBusId = "PCI:1:0:0";
    };
  };
}
