wakatime_api_key: ENC[AES256_GCM,data:JFTmR9hgYgLubeAGv/mZtlCCI53UFeBsg7ADJduPrDS+SoPFqmscpEs=,iv:2/Y4mfVI33qnBf3f2q0UHAsfu26H3ARpODlxQQLo6aU=,tag:cCe9P6dpNFBp1oryk0C6bg==,type:str]
sops:
    age:
        - recipient: age1w4gpvqfdw2w7ly0fjlcaddxlvt3mwd0hvp3rhvk4jtd5m2cmsp4segcmej
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSU0hST2w2bnJzREI5eTN1
            RUhQQVFTaHE3ZlFZa0YrMC9vOHZvVG5sOFMwCkk5UW5acDVucnpJQmhKQXhVY3Br
            OURXc09NbDR1cGlzaHVSSWpta2MrV0UKLS0tIDVDc2ZKSk9sbElnOW50MGNsQTVl
            V2xnbEZEMTl6RGNTNGxhUkZLTGVtNEkKF519aRWUcZ97BsYAWtjPjRDXJSF3Lo07
            /xCHYoKTYfInFOuBhwCn9d0sdO8l1GcW8PHYgSvUDD8WNyEjKXv8IQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1laa24tfw3yf9sms55ydw8h437h7ksyt4alwnsjg3z5569tlc0gmq2ceyvt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbi9wWDROMHZaa2dsS05W
            a1VjWUgwV0dRQ0tDTEs3V1NUY3VTOFE3WlVVCjI0SUY0Z0pIVm1JVzRuN3NhTE16
            ME1zb2QxY2ZlK2NyYm5jTHpVdTJDbGcKLS0tIGN5UEpIamF3UTRvVk0yRzFqVTRa
            ZTdaTldMdWZVK0VSUU5kd2lnbXBPeTgK7svzN0t7zHEQXzAsma9/tFiCVX6TT+Rj
            UdlNGgyZ9ThTrD4yKsCxNzXs6Nuu9Tf51qcoYhoJ4ERVAEeeFrE2hA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sj3axmvypjme2f9m7csxehahj78chnek6dhrhhlv4hqjd4lgd5lq6sehmk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NVdtRWVtWm5Ycll6WlJE
            QlhVRDJrVmNhL3Bnd0JHVm1yVmZGUnpsS2xZCkV2UUNEZy9iTTFEYVlrcXQwc1Nh
            cEYwck41b1VlQVd0QWR2WEg5bW5NRkEKLS0tIDJBcThaWkJMbDBjZnJjay9qZVJB
            aDhDajhCQWEyM0RaeVVXN1E0VkVlRUkKb7W10m4OrblxR2asen4sQoFmy0HAb30x
            br9e70RWCEHRFE0lAxLLXJzrlXMx6nWgh3kg3iCPiWoX0FpmPo63Kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T00:30:56Z"
    mac: ENC[AES256_GCM,data:MotW9xGX4hebPJLeYTcECnMqMPUKM8M36I2OVEoPGK0LMVlF6f3rvYJWvggDYtdpwRwjb6+F1SFcHbSgDskJTZd4klKpNHkX5+D5ZgXXhGBrNG9xF2gZFhv9mgVQxEcJEVil+ZS7mG+gjm/D08cRVj4KJdEnqf4Izyz2E5a8M5M=,iv:mOgHU9VNc4dIClsaXlt5QYQFemA6wv54Bp9/+zULK2s=,tag:CCvIUoA/ZJYNLlabonBNpg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
